# Generated by Django 5.1 on 2025-06-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('detection_time', models.CharField(max_length=1000)),
                ('emotion', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Emotions',
            },
        ),
    ]
