# Generated by Django 5.1 on 2025-06-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emotions',
        ),
    ]
