# Generated by Django 5.1 on 2025-06-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmotionLog',
        ),
    ]
