# Generated by Django 5.1 on 2025-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotions', '0008_delete_emotionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=100)),
                ('emotion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EmotionLog',
            },
        ),
    ]
