# Generated by Django 5.1 on 2025-06-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmotionLog',
        ),
    ]
