# Generated by Django 5.1 on 2025-06-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0015_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmotionLog',
        ),
    ]
