# Generated by Django 5.1 on 2025-06-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0017_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmotionLog',
        ),
    ]
